name: tbddp
channels:
  - defaults
dependencies:
  - black==19.10b0
  - flake8==3.7.9
  - python=3.7.3
  - numpy=1.16.4
  - pandas=0.24.2
  - pip=19.1.1
  - spyder=3.3.6
  - plotly=4.4.1
  - pip:
    - orjson==3.1.2
    - python-dotenv==0.10.3
    - matplotlib==3.1.2
